config/routes.rb
EvadesWebSite::Application.routes.draw do

  resources :cavales

  resources :mailings, :except => :new

  match 'mailings/0/sendNL', :to => 'mailings#sendNL', :as => :send_nl
  match 'mailings/0/importCsv', :to => 'mailings#importCsv', :as => :import_csv
  match 'mailings/0/destroyAll', :to => 'mailings#destroyAll', :as => :destroyAll
    

  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  mount Ckeditor::Engine => '/ckeditor'

  match 'pages/home', :to => 'pages#home', :as => :home_page
  match 'pages/contact', :to => 'pages#contact', :as => :contact_page
  match 'pages/principe', :to => 'pages#principe', :as => :principe_page
  match 'pages/galerie', :to => 'pages#galerie', :as => :galerie_page
  match 'pages/login', :to => redirect("/login")

  match 'candidature' => 'pages#candidature', :as => 'candidature', :via => :get
  match 'candidature' => 'pages#create_candidature', :as => 'candidature', :via => :post

  match 'contact' => 'pages#contact', :as => 'contact', :via => :get
  match 'contact' => 'pages#create_contact', :as => 'contact', :via => :post

  resources :affiche_templates do
    get "genAffiche", :on => :member
    get "genATWithBloc", :on => :member
    get "update_dh", :on => :member
    get "update_lieu", :on => :member
    get "update_teaser", :on => :member
    get "update_drag", :on => :member    
  end

  get "photos/index"  
  match "/photos/" => "photos#index", :as => :photos
  match "/photos/:id" => "photos#show", :as => :show_photos

  resources :lieus, :path => "lieux", :as => :lieus

  resources :spectacles do 
    member do
      get :download
    end
  end

  resources :users, :path => "evades", :as => :users do 
    get "promote_admin", :on => :member
  end

mount Ckeditor::Engine => "/ckeditor"

  root :to => "pages#home"

end

app/models/mailing.rb
class Mailing < ActiveRecord::Base
  attr_accessible :email, :nom

  validates :email, :uniqueness => true
end

app/controllers/mailings_controller.rb
# encoding: utf-8
class MailingsController < ApplicationController

before_filter :authenticate_user!
  
  # GET /mailings
  # GET /mailings.json
  def index
    @mailings = Mailing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mailings }
    end
  end

  # GET /mailings/1
  # GET /mailings/1.json
  def show
    @mailing = Mailing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mailing }
    end
  end

  # GET /mailings/new
  # GET /mailings/new.json
  def new
    @mailing = Mailing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mailing }
    end
  end

  # GET /mailings/1/edit
  def edit
    @mailing = Mailing.find(params[:id])
  end

  # POST /mailings
  # POST /mailings.json
  def create
    @mailing = Mailing.new(params[:mailing])

    respond_to do |format|
      if @mailing.save
        MailingMailer.welcome_email(@mailing).deliver

        format.html { redirect_to :back, notice: 'Mailing was successfully created.' }
        format.json { render json: @mailing, status: :created, location: @mailing }
      else
        flash[:error] = "Cet email est déjà inscrit" 
        format.html { redirect_to :back }
        format.json { render json: @mailing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mailings/1
  # PUT /mailings/1.json
  def update
    @mailing = Mailing.find(params[:id])

    respond_to do |format|
      if @mailing.update_attributes(params[:mailing])
        format.html { redirect_to @mailing, notice: 'Mailing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mailing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailings/1
  # DELETE /mailings/1.json
  def destroy
    @mailing = Mailing.find(params[:id])
    @mailing.destroy

    respond_to do |format|
      format.html { redirect_to mailings_url }
      format.json { head :no_content }
    end
  end

def destroyAll
  @mailings = Mailing.all
  @mailings.each do |mailing|
    mailing.destroy
  end
  redirect_to :back
end

def sendNL
  @spectacle=Spectacle.find_by_titre(params[:Spectacle])
  Mailing.all.each do |mailing|
    MailingMailer.newsletter(@spectacle,mailing,request.protocol, request.host_with_port).deliver
  end
  flash[:notice] = "La newsletter est envoyée!" 
  redirect_to :back
end

def importCsv
  emails = MailingImporter.importemails(params[:csv_file].read)
  emails.each do |email|
    unless Mailing.all.include? email then
      @m = Mailing.new(:email => email)
      @m.save
    end
  end
  redirect_to :back

end



end

app/helpers/mailings_helper.rb
module MailingsHelper
end

app/views/mailings/_form.html.erb
<div class="form-inline">
  <%= form_for(@new_mailing) do |f| %>
    <% if @new_mailing.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@new_mailing.errors.count, "error") %> prohibited this mailing from being saved:</h2>

        <ul>
          <% @new_mailing.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.text_field :nom, :placeholder => "nom" %>

    <%= f.text_field :email ,:placeholder => "email"%>

    <%= f.submit nil , :class => 'btn btn-primary'%>
  <% end %>
</div>

app/views/mailings/_home_form.html.erb
  <%= form_for(@new_mailing, :html => { :class => "form-inline" }) do |f| %>
  <% if @new_mailing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mailing.errors.count, "error") %> prohibited this mailing from being saved:</h2>

      <ul>
      <% @new_mailing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <center>
    <h4>Inscrivez vous à notre mailing list!</h4></br>
    <%= f.text_field :email %>
    <%= f.submit "S'inscrire!", :class => "btn btn-primary" %>
</center>
<% end %>

app/views/mailings/edit.html.erb
<h1>Editing mailing</h1>

<%= render 'form' %>

<%= link_to 'Show', @mailing %> |
<%= link_to 'Back', mailings_path %>

app/views/mailings/index.html.erb
<h1> Envoyer la mailing list </h1>
    <div  class="form-inline"><%= form_tag(send_nl_path, :method => :get) do %>

   <%=   select_tag("Spectacle", options_for_select(Spectacle.all.sort_by{|s| s.start_time}.reject{ |s| (s.start_time-DateTime.now)<0 }.map{|s| s.titre}))%>

      <%= submit_tag "Envoyer!"%>
    <% end %></div>


<h1><%= @mailings.size %> inscrits</h1>

<%= render 'form' %>

<table class="table table-striped">
  <tr>
    <th>Nom</th>
    <th>Email</th>
    <th></th>
    <th></th>
  </tr>

<% @mailings.each do |mailing| %>
  <tr>
    <td><%= mailing.nom %></td>
    <td><%= mailing.email %></td>
    <td><%= link_to 'Edit', edit_mailing_path(mailing) %></td>
    <td><%= link_to 'Destroy', mailing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>


<div class="form-inline">
  <%= form_tag(import_csv_path, :multipart => true) do %>
      <%= file_field_tag :csv_file %>

      <%= submit_tag "importer csv"%>
  <% end %>
</div>


<div class="form-inline">
  <%= form_tag(destroyAll_path) do %>
      <%= submit_tag "Detruire tout!"%>
  <% end %>
</div>

app/views/mailings/new.html.erb
<h1>New mailing</h1>

<%= render 'form' %>

<%= link_to 'Back', mailings_path %>

app/views/mailings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @mailing.nom %>
</p>

<p>
  <b>Email:</b>
  <%= @mailing.email %>
</p>


<%= link_to 'Edit', edit_mailing_path(@mailing) %> |
<%= link_to 'Back', mailings_path %>