config/routes.rb
EvadesWebSite::Application.routes.draw do

  resources :cavales

  resources :mailings, :except => :new

  match 'mailings/0/sendNL', :to => 'mailings#sendNL', :as => :send_nl
  match 'mailings/0/importCsv', :to => 'mailings#importCsv', :as => :import_csv
  match 'mailings/0/destroyAll', :to => 'mailings#destroyAll', :as => :destroyAll
    

  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  mount Ckeditor::Engine => '/ckeditor'

  match 'pages/home', :to => 'pages#home', :as => :home_page
  match 'pages/contact', :to => 'pages#contact', :as => :contact_page
  match 'pages/principe', :to => 'pages#principe', :as => :principe_page
  match 'pages/galerie', :to => 'pages#galerie', :as => :galerie_page
  match 'pages/login', :to => redirect("/login")

  match 'candidature' => 'pages#candidature', :as => 'candidature', :via => :get
  match 'candidature' => 'pages#create_candidature', :as => 'candidature', :via => :post

  match 'contact' => 'pages#contact', :as => 'contact', :via => :get
  match 'contact' => 'pages#create_contact', :as => 'contact', :via => :post

  resources :affiche_templates do
    get "genAffiche", :on => :member
    get "genATWithBloc", :on => :member
    get "update_dh", :on => :member
    get "update_lieu", :on => :member
    get "update_teaser", :on => :member
    get "update_drag", :on => :member    
  end

  get "photos/index"  
  match "/photos/" => "photos#index", :as => :photos
  match "/photos/:id" => "photos#show", :as => :show_photos

  resources :lieus, :path => "lieux", :as => :lieus

  resources :spectacles do 
    member do
      get :download
    end
  end

  resources :users, :path => "evades", :as => :users do 
    get "promote_admin", :on => :member
  end

mount Ckeditor::Engine => "/ckeditor"

  root :to => "pages#home"

end

app/models/lieu.rb
class Lieu < ActiveRecord::Base
  attr_accessible :street,:city,:country, :nom,:latitude,:longitude,:gmaps
  has_many :spectacles

acts_as_gmappable

def gmaps4rails_address
#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
  "#{self.street}, #{self.city}, #{self.country}" 
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

#  validates :avatar, :attachment_presence => true        


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :nom, :prenom, :surnom, :spectacle_ids
  attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "300x200#", :thumb => "100x60#", :large => "800x800>" }

  has_and_belongs_to_many :spectacles
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :only_admin, :only => [:create, :destroy, :promote_admin]
  before_filter :get_spectacles

  # GET /users
  # GET /users.json
  def index
    @users = User.all.shuffle

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def get_spectacles
    @spectacles = Spectacle.find(:all, :order => "start_time")
  end

  # A définir et valider
    
    def promote_admin
      @user = User.find(params[:id])
      @user.update_attribute :admin, !@user.admin
      redirect_to :back
    end

  def only_admin
    redirect_to root_path unless current_user.try(:admin?)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatars_list.html.erb
<li class="span6">
	<span class="thumbnail fond-barrault">
    <center>
		<h4><%=user.surnom%></h4>
		<%= link_to user do %>
				<%= image_tag user.avatar.url(:medium) %>
      	<% end%>
      </br>
  <% if user_signed_in? %>

      	<div class="btn-group">
<% if (user == current_user) || current_user.try(:admin?)%>
  				<button class="btn btn-primary"><%= link_to 'Edit', edit_user_path(user) %></button>
<% end %>
    <% unless user==current_user%>
<% if current_user.try(:admin?)%>
  				<button class="btn btn-primary"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></button>
          <% if user.try(:admin?)%>
            <button class="btn btn-primary"><%= link_to 'Downgrade', promote_admin_user_path(user) %></button>
          <% else %>
            <button class="btn btn-primary"><%= link_to 'Promote admin', promote_admin_user_path(user) %></button>
          <% end %>
          <% end%>

<%end%>

      	</div>

<% end %>
      </center>
    </span>
</li>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prenom %><br />
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :surnom %><br />
    <%= f.text_field :surnom %>
  </div>
    <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
   <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div> <div class="field">
    <%= f.label :avatar %><br />
  <%= f.file_field :avatar %>
</div>
  <p>Spectacles :</p><br />
  <%= collection_select(:user, :spectacle_ids, @spectacles, :id, :titre, {:prompt => " "}, { :multiple => true })%>
  <p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_small_avatar_list.html.erb
  <div class="span2" href="#" rel="tooltip" title=<%= user.surnom %>><%= link_to (image_tag user.avatar.url(:thumb)), user %></div>


  <% content_for(:head) do %>
<%= javascript_include_tag 'jquery'%>
    <script type="text/javascript" charset="utf-8">
$( function($) {
    $("#hint div").tooltip()
});
    </script>

<% end %>

app/views/users/_users_list.html.erb
  <tr>
    <td><%= image_tag user.avatar.url(:thumb) %></td>
    <td><%= user.prenom %></td>
    <td><%= user.nom %></td>
    <td><%= user.surnom %></td>
    <td><%= user.spectacles.count %></td>
    <td>
       <% if user_signed_in? %>

      <div class="btn-group">
  <button class="btn"><%= link_to 'Voir', user %></button>
  <button class="btn"><%= link_to 'Edit', edit_user_path(user) %></button>
  <button class="btn"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    </div>
 <% end %>

</td>     </tr>

app/views/users/_users_list_head.html.erb
 <tr>
 	<th></th>
    <th>Prenom</th> 	
    <th>Nom</th>
    <th>Surnom</th>
    <th>Nombre de spectacles joués</th>
    <th></th>
 </tr>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="page-header"><h1>Qui sommes nous?<% if current_user.try(:admin?)%>
<button class="btn btn-primary pull-right">
<%= link_to 'Nouveau Evadé', new_user_path %>
</button>
<% end %></h1></div>

<p>Ils sont 13 et ils ne sont pas là pour rire. Ils ont déjà affronté toutes les polices de France, joué les filles de l’air pour s’extirper de différentes prisons et perfectionné leur art de bandits sur bien des coffres…</p>

<p>Ils sont les Évadés de la Rue Barrow. </p>

<p>Jeune troupe dynamique de théâtre d’improvisation, les Évadés de la Rue Barrow ont à leur actif plusieurs spectacles devant un public de 40 à 80 personnes dans des bars ou dans leur repaire à Télécom ParisTech. Un spectacle met en scène un présentateur et 5 improvisateurs, accompagnés d’un musicien et un lumiériste, pour une durée d’une à deux heures.</p>

</br>

<!-- <table class="table table-striped table-bordered">

    <thead>
<%= render "users_list_head" %>
  </thead>
<tbody>
<%= render :partial=>"users_list", :collection =>@users, :as => :user %>
</tbody>

</table>
 -->

<span class="row-fluid">

	<ul class="thumbnails">
<%= render :partial=>"avatars_list", :collection =>@users, :as => :user %>
	</ul>
</span>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="page-header">
<h1><%= @user.surnom %></h1>
</div>
<p id="notice"><%= notice %></p>

<%= image_tag @user.avatar.url(:large) %>


<p>
  <b>Nom:</b>
  <%= @user.nom %>
</p>





<p>
  <b>Prenom:</b>
  <%= @user.prenom %>
</p>




<br>

<h3>Casier judiciaire, <%= @user.spectacles.count %> spectacles : </h3>
<table class="table table-striped">
    <thead>
<%= render "spectacles/spectacles_list_head" %>
  </thead>
<tbody>
<%= render :partial=>"spectacles/spectacles_list", :collection =>@user.spectacles, :as => :spectacle %>
</tbody>

</table>
 <% if user_signed_in? %>

<%= link_to 'Edit', edit_user_path(@user) %> |
 <% end %>

<%= link_to 'Back', :back %>