config/routes.rb
EvadesWebSite::Application.routes.draw do

  resources :cavales

  resources :mailings, :except => :new

  match 'mailings/0/sendNL', :to => 'mailings#sendNL', :as => :send_nl
  match 'mailings/0/importCsv', :to => 'mailings#importCsv', :as => :import_csv
  match 'mailings/0/destroyAll', :to => 'mailings#destroyAll', :as => :destroyAll
    

  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  mount Ckeditor::Engine => '/ckeditor'

  match 'pages/home', :to => 'pages#home', :as => :home_page
  match 'pages/contact', :to => 'pages#contact', :as => :contact_page
  match 'pages/principe', :to => 'pages#principe', :as => :principe_page
  match 'pages/galerie', :to => 'pages#galerie', :as => :galerie_page
  match 'pages/login', :to => redirect("/login")

  match 'candidature' => 'pages#candidature', :as => 'candidature', :via => :get
  match 'candidature' => 'pages#create_candidature', :as => 'candidature', :via => :post

  match 'contact' => 'pages#contact', :as => 'contact', :via => :get
  match 'contact' => 'pages#create_contact', :as => 'contact', :via => :post

  resources :affiche_templates do
    get "genAffiche", :on => :member
    get "genATWithBloc", :on => :member
    get "update_dh", :on => :member
    get "update_lieu", :on => :member
    get "update_teaser", :on => :member
    get "update_drag", :on => :member    
  end

  get "photos/index"  
  match "/photos/" => "photos#index", :as => :photos
  match "/photos/:id" => "photos#show", :as => :show_photos

  resources :lieus, :path => "lieux", :as => :lieus

  resources :spectacles do 
    member do
      get :download
    end
  end

  resources :users, :path => "evades", :as => :users do 
    get "promote_admin", :on => :member
  end

mount Ckeditor::Engine => "/ckeditor"

  root :to => "pages#home"

end

app/models/affiche_template.rb
# encoding: utf-8
class AfficheTemplate < ActiveRecord::Base

require 'RMagick'                                       # Pour faire des choses sur les images (ImageMagick)
include Magick

  attr_accessible :nom,:dhheigh, :dhwidth, :dhx, :dhy, :lieuheigh, :lieuwidth, :lieux, :lieuy, :teaserheigh, :teaserwidth, :teaserx, :teasery

	attr_accessible :fond,:fond_with_blocs
  has_attached_file :fond_with_blocs, :styles => { :showPage => "700x990>" }	
  has_attached_file :fond, :styles => { :thumb => "100x100>", :homePage => "350x495>", :showPage => "700x990>" }

 
  
  def fond_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(fond.url(style))
  end



def genATWithBloc
#  attr_accessible  :lieuheigh, :lieuwidth, :lieux, :lieuy, :teaserheigh, :teaserwidth, :teaserx, :teasery

  # ouverture de l'original pour calculer sa taille
  orig = ImageList.new(fond.url.split("?")[0])  
  @or_x,@or_y = orig.columns,orig.rows
  orig.destroy!

  # ouverture de l'image a modifier
  img = ImageList.new(fond.url(:homePage).split("?")[0])

  # calcul des coeffs ajustés
  @dhx_i = ( dhx.to_f / @or_x * img.columns ).to_i
  @dhx_o = ( ( dhx.to_f + dhwidth )/ @or_x * img.columns ).to_i
  @dhy_i = ( dhy.to_f / @or_y * img.rows ).to_i
  @dhy_o = ( ( dhy.to_f + dhheigh )/ @or_y * img.rows ).to_i
  @dh_size=getPointSize("Date et Heure",img,0.9*dhwidth.to_f / @or_x)

  # Ajout du descriptif
  txt = Draw.new
  txt.pointsize = @dh_size
  img.annotate(txt,@dhx_o-@dhx_i,@dhy_o-@dhy_i,@dhx_i,@dhy_i, "Date et Heure"){
    txt.gravity = CenterGravity
    txt.stroke = 'red'
    txt.fill = 'transparent'
    txt.font_weight = Magick::BoldWeight
  }

  @lieux_i = ( lieux.to_f / @or_x * img.columns ).to_i
  @lieux_o = ( ( lieux.to_f + lieuwidth )/ @or_x * img.columns ).to_i
  @lieuy_i = ( lieuy.to_f / @or_y * img.rows ).to_i
  @lieuy_o = ( ( lieuy.to_f + lieuheigh )/ @or_y * img.rows ).to_i
  @lieu_size=getPointSize("Lieu",img,0.9*lieuwidth.to_f / @or_x)

  # Ajout du descriptif
  txt2 = Draw.new
  txt2.pointsize = @lieu_size
  img.annotate(txt2,@lieux_o-@lieux_i,@lieuy_o-@lieuy_i,@lieux_i,@lieuy_i, "Lieu"){
    txt2.gravity = CenterGravity
    txt2.stroke = 'red'
    txt2.fill = 'transparent'
    txt2.font_weight = Magick::BoldWeight
  }

  @teaserx_i = ( teaserx.to_f / @or_x * img.columns ).to_i
  @teaserx_o = ( ( teaserx.to_f + teaserwidth )/ @or_x * img.columns ).to_i
  @teasery_i = ( teasery.to_f / @or_y * img.rows ).to_i
  @teasery_o = ( ( teasery.to_f + teaserheigh )/ @or_y * img.rows ).to_i
  @teaser_size=getPointSize("Teaser",img,0.9*teaserwidth.to_f / @or_x)

  # Ajout du descriptif
  txt3 = Draw.new
  txt3.pointsize = @teaser_size
  img.annotate(txt3,@teaserx_o-@teaserx_i,@teasery_o-@teasery_i,@teaserx_i,@teasery_i, "Teaser"){
    txt3.gravity = CenterGravity
    txt3.stroke = 'red'
    txt3.fill = 'transparent'
    txt3.font_weight = Magick::BoldWeight
  }

  rect = Draw.new
  rect.stroke('red').stroke_width(1)
  rect.fill('transparent')
  rect.rectangle(@dhx_i,@dhy_i,@dhx_o,@dhy_o)
  rect.rectangle(@lieux_i,@lieuy_i,@lieux_o,@lieuy_o)
  rect.rectangle(@teaserx_i,@teasery_i,@teaserx_o,@teasery_o)
  rect.draw(img)

  file = Tempfile.new('my_picture')
  img.flatten_images.write(file.path)

	self.update_attributes(:fond_with_blocs => file)
	fond_with_blocs.reprocess!




#    send_data img.to_blob, :stream => 'false', :filename => 'test.jpg', :type => 'image/jpeg', :disposition => 'inline'

end

def creerAffiche!(spectacle,teaser = "")
#    img.format = 'jpeg'
    file = Tempfile.new('my_picture')
    creerRMAffiche(spectacle,teaser).flatten_images.write(file.path)

	spectacle.update_attributes(:affiche => file)
	spectacle.affiche.reprocess!

end

def creerAffiche(spectacle,teaser = "")
	    return creerRMAffiche(spectacle,teaser)
	end

  handle_asynchronously :creerAffiche!
  handle_asynchronously :creerAffiche

private

  def creerRMAffiche(spectacle,teaser = "")
  @lieu=Lieu.find(spectacle.lieu_id)
  lieuMessage="#{@lieu.nom}\n#{@lieu.street}\n#{@lieu.city}"
  frenchWeekdays = ["Dimanche","Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche"]
  frenchMonths = ["Janvier","Fevrier","Mars","Avril","Mai","Juin","Juillet","Aout","Septembre"]
  @dh=[frenchWeekdays[spectacle.start_time.wday.to_i],spectacle.start_time.mday.to_s,frenchMonths[spectacle.start_time.mon]].join(" ")
  @dh+=" à #{spectacle.start_time.hour}h#{sprintf('%02d',spectacle.start_time.min)}"


  img = ImageList.new(fond.url.split("?")[0])
  @dh_size=getPointSize(@dh,img,dhwidth.to_f / img.columns.to_f)

  # Ajout de la date et de l'heure
  txt = Draw.new
  txt.pointsize = @dh_size
  img.annotate(txt,dhwidth,dhheigh,dhx,dhy, @dh){
    txt.gravity = CenterGravity
    txt.stroke = '#000000'
    txt.fill = '#ffffff'
    txt.font_weight = Magick::BoldWeight
  }

  # Ajout du teaser
  unless spectacle.teaser.empty? && teaser.empty? then
  	@teaser_to_use = spectacle.teaser
  	@teaser_to_use = teaser unless teaser.empty?

    @pointsize=getPointSizeBySurface(@teaser_to_use,img,teaserwidth.to_f / img.columns.to_f,teaserheigh.to_f / img.rows.to_f) 

    txt2 = Draw.new
    txt2.pointsize = @pointsize
    txt2.pointsize = @dh_size * 0.7 if @pointsize>(@dh_size * 0.5) 
    @lines = constructLines(@teaser_to_use,txt2,teaserwidth,img)
    tx_height=txt2.get_type_metrics(img,@teaser_to_use)[4]
    tx_height+=tx_height*0.2

    decay=teasery
    @lines.each do |l|
      img.annotate(txt2,teaserwidth,teaserheigh,teaserx,decay, l){
        txt2.gravity = NorthGravity
        txt2.stroke = '#000000'
        txt2.fill = '#ffffff'
        txt2.font_weight = Magick::BoldWeight
      }
      decay+=tx_height
    end
  end

  # Ajout du lieu
  txt3 = Draw.new 
  txt3.pointsize = @dh_size * 0.3
  lieu_texte="#{@lieu.nom}\n#{@lieu.street}\n#{@lieu.city}"
  tx_height=txt3.get_type_metrics(img,lieu_texte)[4]
  tx_height+=tx_height*0.2  
  decay=lieuy
  lieu_texte.split("\n").each do |l|
    img.annotate(txt3,lieuwidth,lieuheigh,lieux,decay, l){
        txt3.gravity = NorthWestGravity
        txt3.stroke = '#000000'
        txt3.fill = '#ffffff'
        txt3.font_weight = Magick::BoldWeight
    }
    decay+=tx_height
  end

  # ajout du site web
  txt4 = Draw.new   
  txt4.pointsize = @dh_size * 0.3
  ws_texte = "www.ruebarrow.fr"
  tx_height=txt4.get_type_metrics(img,ws_texte)[4]   
  img.annotate(txt4,img.columns,tx_height,0,-img.rows+tx_height,ws_texte){
      txt4.gravity = SouthGravity
      txt4.stroke = '#000000'
      txt4.fill = '#ffffff'
      txt4.font_weight = Magick::BoldWeight
  }

  return img
end


	def getPointSize(texte,img,sizePortion)

		# get one character size
		txt = Draw.new
		txt.pointsize = 10
		size = txt.get_type_metrics(img,texte)
		width,height = size[3],size[4]

		# nb de pixels a avoir par lettre
		nbPixByLetter = img.columns.to_f * sizePortion

		return (nbPixByLetter / width * 10).to_i

	end


	def getPointSizeBySurface(texte,img,sizePortionX,sizePortionY) 

		# get one character size
		txt = Draw.new
		txt.pointsize = 10
		size = txt.get_type_metrics(img,texte)
		width,height = size[3],size[4]		

		# aire de la cellule dans laquelle on veut mettre le texte
		aire = img.columns.to_f * img.rows.to_f * sizePortionX.to_f * sizePortionY.to_f
		ratioTxt = height.to_f / width.to_f 		

		# calcul de la taille en point
		new_Width  = Math.sqrt( aire / ratioTxt ).to_i
		lettersize = new_Width / texte.size
		pointsize = (new_Width / width * 10).to_i		
		

		return pointsize		

	end

	def constructLines(texte,txt,width,img)

		width_tot = txt.get_type_metrics(img,texte)[3]
		lettersize = width_tot / texte.size		

		  # construct lines
		words=texte.split(" ")
		lines=[]
		localLine=""
		words.each do |w|
		  if((localLine+w).size * lettersize) < width then
		    localLine+=" "+w
		  else
		    lines << localLine
		    localLine=w
		  end
		end
		lines << localLine		

		return lines		

	end

end

app/controllers/affiche_templates_controller.rb
# encoding: utf-8
class AfficheTemplatesController < ApplicationController
  # GET /affiche_templates
  # GET /affiche_templates.json

before_filter :authenticate_user!
before_filter :findATemplate, :except => [:index, :new, :create]

require 'RMagick'                                       # Pour faire des choses sur les images (ImageMagick)
include Magick

  def findATemplate
    @affiche_template = AfficheTemplate.find(params[:id])
  end

  def index
    @affiche_templates = AfficheTemplate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @affiche_templates }
    end
  end

  # GET /affiche_templates/1
  # GET /affiche_templates/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @affiche_template }
    end
  end

  # GET /affiche_templates/new
  # GET /affiche_templates/new.json
  def new
    @affiche_template = AfficheTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @affiche_template }
    end
  end

  # GET /affiche_templates/1/edit
  def edit
 
  end

  # POST /affiche_templates
  # POST /affiche_templates.json
  def create
    @affiche_template = AfficheTemplate.new(params[:affiche_template])

    respond_to do |format|
      if @affiche_template.save
        format.html { redirect_to @affiche_template, notice: 'Affiche template was successfully created.' }
        format.json { render json: @affiche_template, status: :created, location: @affiche_template }
      else
        format.html { render action: "new" }
        format.json { render json: @affiche_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /affiche_templates/1
  # PUT /affiche_templates/1.json
  def update

    respond_to do |format|
      if @affiche_template.update_attributes(params[:affiche_template])
        @affiche_template.genATWithBloc
       format.html { redirect_to @affiche_template, notice: 'Affiche template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @affiche_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiche_templates/1
  # DELETE /affiche_templates/1.json
  def destroy
    @affiche_template.destroy

    respond_to do |format|
      format.html { redirect_to affiche_templates_url }
      format.json { head :no_content }
    end
  end
def genAffiche
  @spectacle=Spectacle.find_by_titre(params[:Spectacle])

  if(params[:Ecraser]) then
      @affiche_template .creerAffiche!(@spectacle,params[:teaser])
      redirect_to @spectacle
  else
      send_data @affiche_template.creerAffiche(@spectacle,params[:teaser]).to_blob, :stream => 'false', :filename => 'test.jpg', :type => 'image/jpeg', :disposition => 'inline'
  end
end



end

app/helpers/affiche_templates_helper.rb
module AfficheTemplatesHelper
end

app/views/affiche_templates/_form.html.erb
<%= form_for(@affiche_template) do |f| %>
  <% if @affiche_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@affiche_template.errors.count, "error") %> prohibited this affiche_template from being saved:</h2>

      <ul>
      <% @affiche_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :teaser_width %><br />
    <%= f.number_field :teaserwidth %>
  </div>
  <div class="field">
    <%= f.label :teaser_heigh %><br />
    <%= f.number_field :teaserheigh %>
  </div>
  <div class="field">
    <%= f.label :teaser_x %><br />
    <%= f.number_field :teaserx %>
  </div>
  <div class="field">
    <%= f.label :teaser_y %><br />
    <%= f.number_field :teasery %>
  </div>
  <div class="field">
    <%= f.label :lieu_width %><br />
    <%= f.number_field :lieuwidth %>
  </div>
  <div class="field">
    <%= f.label :lieu_heigh %><br />
    <%= f.number_field :lieuheigh %>
  </div>
  <div class="field">
    <%= f.label :lieu_x %><br />
    <%= f.number_field :lieux %>
  </div>
  <div class="field">
    <%= f.label :lieu_y %><br />
    <%= f.number_field :lieuy %>
  </div>
  <div class="field">
    <%= f.label :dh_width %><br />
    <%= f.number_field :dhwidth %>
  </div>
  <div class="field">
    <%= f.label :dh_heigh %><br />
    <%= f.number_field :dhheigh %>
  </div>
  <div class="field">
    <%= f.label :dh_x %><br />
    <%= f.number_field :dhx %>
  </div>
  <div class="field">
    <%= f.label :dh_y %><br />
    <%= f.number_field :dhy %>
  </div>
    <div class="field">
    <%= f.label :fond %><br />
  <%= f.file_field :fond %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/affiche_templates/_jcrop_updater.html.erb
<% content_for(:head) do %>

<%= stylesheet_link_tag "jquery.Jcrop" %>
<%= javascript_include_tag "jquery.Jcrop.min" %>
    <script type="text/javascript" charset="utf-8">
    $(function() {
 	    $('#cropbox').Jcrop({
		 	<% @iratio = @affiche_template.fond_geometry(:homePage).width.to_f / @affiche_template.fond_geometry(:original).width.to_f%>

	 			 			 	
 	   		onChange: update_crop,
       		onSelect: update_crop,
    		setSelect: [<%= (lieux.to_f*@iratio).to_i%>,<%= (lieuy.to_f*@iratio).to_i%>,<%= ((lieux.to_f+lieuwidth)*@iratio).to_i%>,<%= ((lieuy.to_f+lieuheigh)*@iratio).to_i%>]
	  	});
	});

	function update_crop(coords) {
		 var ratio = <%= @affiche_template.fond_geometry(:original).width %> / <%= @affiche_template.fond_geometry(:homePage).width %>;
 	  	$("#lieux").val(Math.round(coords.x * ratio));
  		$("#lieuy").val(Math.round(coords.y * ratio));
  		$("#lieuwidth").val(Math.round(coords.w * ratio));
  		$("#lieuheigh").val(Math.round(coords.h * ratio)); }

    </script>

<% end %>

<%= image_tag @affiche_template.fond.url(:homePage), :id => "cropbox" %>

app/views/affiche_templates/edit.html.erb
<h1>Editing affiche_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @affiche_template %> |
<%= link_to 'Back', affiche_templates_path %>

app/views/affiche_templates/index.html.erb
<h1>Listing affiche_templates</h1>

<table>


<% @affiche_templates.each do |affiche_template| %>
  <tr>
    <td><%= image_tag affiche_template.fond.url(:thumb) %></td>
    <td><b><%= affiche_template.nom %></b></td>
    <td><%= link_to 'Show', affiche_template %></td>
    <td><%= link_to 'Edit', edit_affiche_template_path(affiche_template) %></td>
    <td><%= link_to 'Destroy', affiche_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Affiche template', new_affiche_template_path %>

app/views/affiche_templates/new.html.erb
<h1>New affiche_template</h1>

<%= render 'form' %>

<%= link_to 'Back', affiche_templates_path %>

app/views/affiche_templates/show.html.erb
<h1><%= @affiche_template.nom %></h1>

<button class="btn btn-primary"><%= link_to "Positionner la date",update_dh_affiche_template_path(@affiche_template)%></button>
<button class="btn btn-primary"><%= link_to "Positionner le lieu",update_lieu_affiche_template_path(@affiche_template)%></button>
<button class="btn btn-primary"><%= link_to "Positionner le teaser",update_teaser_affiche_template_path(@affiche_template)%></button>
<button class="btn btn-primary"><%= link_to "A l'ancienne!",edit_affiche_template_path(@affiche_template)%></button>

<span class="row">
  <span class="span6">
    <%= image_tag @affiche_template.fond_with_blocs.url(:showPage) %>
  </span>
  <span class="span6">
    <h3> Générateur d'affiches </h3>
    <%= form_tag(genAffiche_affiche_template_path(@affiche_template), :method => :get) do %>
      <div class="field">
      <%= label_tag "Teaser" %>
      <%= text_area_tag "teaser" %>
    </div>

      
 <%=   select_tag("Spectacle", options_for_select(Spectacle.all.sort_by{|s| s.start_time}.reject{ |s| (s.start_time-DateTime.now)<0 }.map{|s| s.titre}))%>
       <div class="field">
      <%= check_box_tag "Ecraser" %><%= label_tag "Ecraser l'affiche du spectacle?" %>
      
    </div>
      <%= submit_tag "Générer!", :class => "btn btn-primary"%>

    <% end %>


    
  </span>

</span>
<span class="row">



  <span class="span12">
    <h4> Infos </h4>
    <ul>
      <li>Teaser width: <%= @affiche_template.teaserwidth %></li>
      <li>Teaser heigh: <%= @affiche_template.teaserheigh %></li>
      <li>Teaser x: <%= @affiche_template.teaserx %></li>
      <li>Teaser y: <%= @affiche_template.teasery %></li>
      <li>Lieu width: <%= @affiche_template.lieuwidth %></li>
      <li>Lieu heigh: <%= @affiche_template.lieuheigh %></li>
      <li>Lieu x: <%= @affiche_template.lieux %></li>
      <li>Lieu y: <%= @affiche_template.lieuy %></li>
      <li>Dh width: <%= @affiche_template.dhwidth %></li>
      <li>Dh heigh: <%= @affiche_template.dhheigh %></li>
      <li>Dh x: <%= @affiche_template.dhx %></li>
      <li>Dh y: <%= @affiche_template.dhy %></li>
    </ul>

  </span>
</span>


<span class="row">
<span class="span12">

<%= link_to 'Edit', edit_affiche_template_path(@affiche_template) %> |
<%= link_to 'Back', affiche_templates_path %>
</span>
</span>

app/views/affiche_templates/update_dh.html.erb
<h1> Update DH </h1>
<%= render :partial => "jcrop_updater", :locals => { :lieux => @affiche_template.dhx, :lieuy => @affiche_template.dhy, :lieuwidth => @affiche_template.dhwidth, :lieuheigh => @affiche_template.dhheigh } %>


<%= form_for @affiche_template do |f| %>
  <% [[:dhx,:lieux], [:dhy,:lieuy], [:dhwidth,:lieuwidth], [:dhheigh,:lieuheigh]].each do |attribute,id| %>
    <%= f.hidden_field attribute, :id => id %>
  <% end %>
  <p><%= f.submit "Mettre à jour", :class => "btn btn-primary" %></p>
<% end %>

app/views/affiche_templates/update_drag.html.erb
<% content_for(:head) do %>
<%= javascript_include_tag 'jquery-ui'%>
  <style>
  #draggable { width: 150px; height: 150px; padding: 0.5em; }
  </style>
    <script type="text/javascript" charset="utf-8">
		$(function() {
		  $( "#draggable" ).draggable();
		});
    </script>

<% end %>

<div id="draggable" class="ui-widget-content">
  <p>Drag me around</p>
</div>

app/views/affiche_templates/update_lieu.html.erb
<h1> Update Lieu </h1>
<%= render :partial => "jcrop_updater", :locals => { :lieux => @affiche_template.lieux, :lieuy => @affiche_template.lieuy, :lieuwidth => @affiche_template.lieuwidth, :lieuheigh => @affiche_template.lieuheigh } %>


<%= form_for @affiche_template do |f| %>
  <% [[:lieux,:lieux], [:lieuy,:lieuy], [:lieuwidth,:lieuwidth], [:lieuheigh,:lieuheigh]].each do |attribute,id| %>
    <%= f.hidden_field attribute, :id => id %>
  <% end %>
  <p><%= f.submit "Mettre à jour", :class => "btn btn-primary" %></p>
<% end %>