config/routes.rb
EvadesWebSite::Application.routes.draw do

  resources :cavales

  resources :mailings, :except => :new

  match 'mailings/0/sendNL', :to => 'mailings#sendNL', :as => :send_nl
  match 'mailings/0/importCsv', :to => 'mailings#importCsv', :as => :import_csv
  match 'mailings/0/destroyAll', :to => 'mailings#destroyAll', :as => :destroyAll
    

  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  mount Ckeditor::Engine => '/ckeditor'

  match 'pages/home', :to => 'pages#home', :as => :home_page
  match 'pages/contact', :to => 'pages#contact', :as => :contact_page
  match 'pages/principe', :to => 'pages#principe', :as => :principe_page
  match 'pages/galerie', :to => 'pages#galerie', :as => :galerie_page
  match 'pages/login', :to => redirect("/login")

  match 'candidature' => 'pages#candidature', :as => 'candidature', :via => :get
  match 'candidature' => 'pages#create_candidature', :as => 'candidature', :via => :post

  match 'contact' => 'pages#contact', :as => 'contact', :via => :get
  match 'contact' => 'pages#create_contact', :as => 'contact', :via => :post

  resources :affiche_templates do
    get "genAffiche", :on => :member
    get "genATWithBloc", :on => :member
    get "update_dh", :on => :member
    get "update_lieu", :on => :member
    get "update_teaser", :on => :member
    get "update_drag", :on => :member    
  end

  get "photos/index"  
  match "/photos/" => "photos#index", :as => :photos
  match "/photos/:id" => "photos#show", :as => :show_photos

  resources :lieus, :path => "lieux", :as => :lieus

  resources :spectacles do 
    member do
      get :download
    end
  end

  resources :users, :path => "evades", :as => :users do 
    get "promote_admin", :on => :member
  end

mount Ckeditor::Engine => "/ckeditor"

  root :to => "pages#home"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :inscriptionML,:newCandidature

  def inscriptionML
  	@new_mailing=Mailing.new
  end

  def newCandidature
  	@new_candidature=Candidature.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_left_nav_bar.html.erb
<%= link_to (image_tag 'luneMenu.png'), home_page_path , :class => "brand"%>
<div class="pull-right">
<%= render 'application/su_menu' %>
</div>


    <ul class="nav nav-list ">
      <li><%= link_to "home", home_page_path %></li>
      <li><%= link_to "Spectacles", spectacles_path %></li>   
      <li><%= link_to "News", cavales_path %></li>       
      <li><%= link_to "Contact", contact_page_path %></li>
      <li><%= link_to "Qui sommes nous?", users_path%></li>
      <li><%= link_to "Nos planques", lieus_path %></li>
      <li><%= link_to "Principe", principe_page_path %></li>
      <li><%= link_to "Galerie", photos_path %></li>         
    </ul>

app/views/application/_nav_bar.html.erb
<div class="navbar navbar-inverse">

  <div class="navbar-inner">

<!--     <a class="brand" href="home_page_path"><%= image_tag "top.png", :class => "brand"%></a> -->


    <ul class="nav">
      <li class="active"><%= link_to "home", home_page_path %></li>
      <li><%= link_to "Spectacles", spectacles_path %></li>   
      <li><%= link_to "News", cavales_path %></li>       
      <li><%= link_to "Contact", contact_page_path %></li>
      <li><%= link_to "Qui sommes nous?", users_path%></li>
      <li><%= link_to "Nos planques", lieus_path %></li>
      <li><%= link_to "Principe", principe_page_path %></li>
      <li><%= link_to "Galerie", photos_path %></li>         
    </ul>


<div class="dropdown pull-right">
  <button class="btn dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
<% if user_signed_in? %>
    <li><%= link_to 'Gestion de la mailing list', mailings_path %></li>    
    <li><%= link_to 'Gestion des spectacles', spectacles_path %></li>
    <li><%= link_to 'Gestion des lieux', lieus_path %></li>
    <li><%= link_to 'Gestion des Evadés', users_path %></li>
    <li class="divider"></li>
    <li><%= link_to 'Nouveau spectacle', new_spectacle_path %></li>
    <li><%= link_to 'Nouveau lieu', new_lieu_path %></li>
    <li><%= link_to 'Nouvel Evadé', new_user_path %></li>
    <li class="divider"></li>
    <li><%= link_to 'Générateur d\'affiches', affiche_templates_path %></li> 
     <li class="divider"></li>
   <li><%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete %></li>  
<% else %>
  <li><%= link_to "Se connecter", "login" %></li>
<%end%>
  </ul>


</div>

  </div>

app/views/application/_side_bar.html.erb
<%= render "application/left_nav_bar" %>	
</br>
<div class="well">
<%= render 'mailings/home_form' %>
<%= render 'widgets/join_modal' %>
</div>

app/views/application/_standard_after_body.html.erb
<footer>
   	<p>Les Evadés de la rue barrow</p>
	<%= yield :scripts %> 

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34856449-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</footer>


</div>



</body>
</html>

app/views/application/_standard_before_body.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Les Évadés de la rue Barrow - Improvisation théâtrale</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application"%>
  <%= javascript_include_tag 'jquery.min'%>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>

</head>
<body>

		<div class="container">

app/views/application/_su_menu.html.erb
<div class="btn-group">
  <a class="btn dropdown-toggle btn-primary" data-toggle="dropdown" href="#">
     <i class="icon-cog"></i>
   
  </a>
  <ul class="dropdown-menu">
<% if user_signed_in? %>
    <li><%= link_to 'Gestion de la mailing list', mailings_path %></li>    
    <li><%= link_to 'Gestion des spectacles', spectacles_path %></li>
    <li><%= link_to 'Gestion des lieux', lieus_path %></li>
    <li><%= link_to 'Gestion des Evadés', users_path %></li>
    <li class="divider"></li>
    <li><%= link_to 'Nouveau spectacle', new_spectacle_path %></li>
    <li><%= link_to 'Nouveau lieu', new_lieu_path %></li>
    <li><%= link_to 'Nouvel Evadé', new_user_path %></li>
    <li class="divider"></li>
    <li><%= link_to 'Générateur d\'affiches', affiche_templates_path %></li> 
     <li class="divider"></li>
       <li><%= link_to 'Réunions ca', reunion_cas_path %></li>    
     <li class="divider"></li>
   <li><%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete %></li>  
<% else %>
  <li><%= link_to "Se connecter", "login" %></li>
<%end%>
  </ul>
</div>